### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Sim4n6** [PatrikFehrenbach/vilicus#13]
I would like to contribute more. And for that why don't we set up a roadmap ;-) a kind of a to-do list if you want.

and please enable private vulnerability reporting for this repository, ... https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by PatrikFehrenbach** [comment]
I'm loving the idea, but at the moment, the application is only suitable for local usage. The API doesn't have any authentication, and the data isn't sanitized yet.

I just started this project on Friday night, and honestly, I have no clue where it's gonna go from here.

I don't wanna make things too complicated right now, so I'll save those security features you mentioned for later down the road.

But hey, feel free to go ahead and fork the repo if you're interested!
