### ISSUE TITLE
Two services 

### ISSUE THREAD

**Issue by Sim4n6** [PatrikFehrenbach/vilicus#3]
Hi

I 'm just wondering the docker compose can have two services mongodb be run runpy file right?

**Comment by PatrikFehrenbach** [comment]
hey @Sim4n6 

absolutely, two services would make more sense.

**Comment by PatrikFehrenbach** [comment]
fixed by https://github.com/PatrikFehrenbach/vilicus/commit/4444ca0ea65dba3fd87ae7c806ebea7266e3aec5
